#!/bin/bash
# Simple watchdog script to check process is alive or dead

while [ 1 ]
    do
    if [ "$(pidof aquariuni)" ] 
    then
        sleep 30
    else
        sudo aquariuni &> /dev/null &
        sleep 30
    fi
done
